# This is a basic workflow to help you get started with Actions

name: Slightly-comples-date-printing-flow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
jobs:
  
  job-1:
    name: job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Show date on ubuntu
        run: |
          dt=$(date)
          echo $dt
  job-2:
    name: job2
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Show date on windows
        run: Get-Date
        
  job-3:
    name: job3
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Show date on macos
        run: |
          dt=$(date)
          echo $dt
  job-4:
    runs-on: windows-latest
    needs: [job-1, job-2, job-3]
    name: job4
    steps:
      - uses: actions/checkout@v3
      - name: Show date on windows when all jobs done
        run: Get-Date
      - run: sleep 30
    
    
    
      

